### ISSUE TITLE
input file: macrel.out.all_orfs.faa vs macrel.out.smorfs.faa

### ISSUE THREAD

**Issue by GaioTransposon** [BigDataBiology/macrel#27]
Hi Luis, 

I ran macrel contigs but it got interrupted because of the peptides issue (now solved). 

That means I have (I think) the input file ready to feed to macrel peptides without having to run starting from the contigs again.
 
Now, as macrel contigs produced TWO output files being: 
macrel.out.all_orfs.faa
macrel.out.smorfs.faa

Should macrel peptides be run on one, or the other, or both? 

Example: 
```
macrel peptides \
    --fasta macrel.out.all_orfs.faa \    <- or : macrel.out.smorfs.faa or macrel.out.*.faa   ???
    --output out_peptides \
    -t 8
```

Thank you!
Dany

**Comment by celiosantosjr** [comment]
Hi Daniela,

Thank you for your question. Ideally, the best would be you rerun all steps from the beginning, since we do not know if the predictions ended correctly. However, as the files were generated and you want to give it a shot, the output "all_orfs" contains orfs of all sizes, therefore it should not be used. On the other side, the one called "smorfs" contains only peptides ranging from 10 to 100 amino acids in length, and was designed to go through the pipeline.

Best,
C.
