### ISSUE TITLE
running problem

### ISSUE THREAD

**Issue by aslangabriel99** [BigDataBiology/macrel#59]
Hi, I have test it with my own data. The warining message was listed as follows"/opt/conda/lib/python3.10/site-packages/sklearn/base.py:299: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.22.1 when using version 1.2.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn("
would you like to help me fix it? thanks a lot

**Comment by celiosantosjr** [comment]
Dear aslangabriel99,

This is due to the format we saved the model and although the warning
message may seem terrifying is just saying that with time these versioning
incompatibilities may lead to problems.
In the next database update, we intend to use joblib to save these models,
eliminating this warning. For now, you may keep using Macrel without any
problems, although the warning message is present.

Best regards,
Celio
