### ISSUE TITLE
If RNA metagenome sequence or  transcriptosome  raw data can be used for macrel analysis

### ISSUE THREAD

**Issue by aslangabriel99** [BigDataBiology/macrel#62]
Hi, I seached metagomic raw data from ncbi and found some sra labeled with RNA metagenomics. So I wonder if those data can be used with this tool？

**Comment by celiosantosjr** [comment]
That's a good question, Aslangabriel99. We did not benchmark its use in transcriptomic data, however, the rationale says it is possible to extract AMP info from metaT.

Have on mind that it may work only for bacterial transcriptomics (no eukaryotes, splicing messes things up) and that is because the assembly tool of Macrel's choice is Megahit. A work around this issue is feeding Macrel with your contigs and after that, it should work as normal as for metaG, with prodigal predicting the genes - again prokaryotic genes. As it is transcriptomics, it is wise to exclude genes found in the antisense strands (so pay attention to the sense of the smORFs). Taking these measures should ensure pretty much decent results if any.

**Comment by celiosantosjr** [comment]
You may find interesting the AMPSphere, a resource we put together with almost 1 million AMPs from more than 64k metaG and almost 100k genomes. Pay a visit to our website at: https://ampsphere.big-data-biology.org/

There you will be able to find several kinds of info for each AMP, their classification into families and their biochemical features. Information about their taxonomy and geographical distribution are also available. AMPs from 72 different habitats are compiled with extensive info and their gene sequences.

**Comment by aslangabriel99** [comment]
Thanks a lot for your help. I also try to detect AMPs from virome of scorpions which just offered transciotpome data, however the availble tools were desgined for amphibians and insect. Would you mind giving me some points?&nbsp;


477684452
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Celio ***@***.***&gt;; 
发送时间: 2023年5月23日(星期二) 上午8:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BigDataBiology/macrel] If RNA metagenome sequence or  transcriptosome  raw data can be used for macrel analysis (Issue #62)





 
You may find interesting the AMPSphere, a resource we put together with almost 1 million AMPs from more than 64k metaG and almost 100k genomes. Pay a visit to our website at: https://ampsphere.big-data-biology.org/
 
There you will be able to find several kinds of info for each AMP, their classification into families and their biochemical features. Information about their taxonomy and geographical distribution are also available. AMPs from 72 different habitats are compiled with extensive info and their gene sequences.

**Comment by celiosantosjr** [comment]
Hi, 

Your demand was already answered in the google discussion group for ampsphere-users, please pay a visit there. I am now closing this issue.

Best,
Celio
